trigger:
  branches:
    include:
      - main

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.9'
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'
    - script: |
        pip install -r requirements.txt
        python -m pip install -e .
      displayName: 'Install package'

- stage: Test
  displayName: Test
  dependsOn: Build
  jobs:
  - job: TestJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.9'
    - script: |
        pip install -r requirements.txt
        pytest -q
      displayName: 'Run pytest'

- stage: Deploy_Staging
  displayName: Deploy to Staging
  dependsOn: Test
  jobs:
  - deployment: DeployStaging
    displayName: Deploy to App Service Staging Slot
    environment: 'staging'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: '<YOUR-SERVICE-CONNECTION>'
              appType: 'webAppLinux'
              appName: '<APP_NAME>'
              resourceGroupName: '<RESOURCE_GROUP>'
              package: '$(System.DefaultWorkingDirectory)'
              slotName: 'staging'
          - script: |
              echo "Deployed to staging slot"
            displayName: 'Post-deploy step'

- stage: ManualApproval
  displayName: Manual approval before prod
  dependsOn: Deploy_Staging
  jobs:
  - job: WaitForApproval
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: ManualValidation@0
      inputs:
        notifyUsers: '<approver-azure-devops-email>'
        instructions: 'Please verify the staging deployment and approve to continue to production.'
        onTimeout: 'reject'

- stage: Deploy_Prod
  displayName: Deploy to Production (Blue/Green swap)
  dependsOn: ManualApproval
  jobs:
  - job: SwapSlots
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: '<YOUR-SERVICE-CONNECTION>'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az webapp deployment slot swap --resource-group <RESOURCE_GROUP> --name <APP_NAME> --source staging --target production
